### ISSUE TITLE
Attendees endpoint

### ISSUE THREAD

**Issue by glitchedmob** [sgf-web-devs/web-devs-app-backend#4]
Should list all of the currently checked in attendees. The mobile app (and the admin app) will hit this endpoint to get the initial list of attendees, then connect to pusher for updates.

**Comment by jason-klein** [comment]
Taking

**Comment by jason-klein** [comment]
Complete. See Pull Request 17 (https://github.com/sgf-web-devs/web-devs-app-backend/pull/17)

**Comment by glitchedmob** [comment]
Closed by #17
